(deftheme mariana-theme
  "Created 2018-02-10.")

(custom-theme-set-faces
 'mariana-theme
 '(default ((t (:family "Monaco" :foundry "nil" :width normal :height 130 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#bbc2cf" :background "#282c34" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#51afef"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#51afef"))))
 '(highlight ((t (:foreground "#1B2229" :background "#51afef"))))
 '(region ((t (:background "#42444a"))))
 '(shadow ((t (:foreground "#5B6268"))))
 '(secondary-selection ((t (:background "#3f444a"))))
 '(trailing-whitespace ((t (:background "#ff6c6b"))))
 '(font-lock-builtin-face ((t (:foreground "#c678dd"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#5B6268"))))
 '(font-lock-constant-face ((t (:foreground "#a9a1e1"))))
 '(font-lock-doc-face ((t (:foreground "#83898d" :inherit (font-lock-comment-face)))))
 '(font-lock-function-name-face ((t (:foreground "#c678dd"))))
 '(font-lock-keyword-face ((t (:foreground "#51afef"))))
 '(font-lock-negation-char-face ((t (:foreground "#51afef" :inherit (bold)))))
 '(font-lock-preprocessor-face ((t (:foreground "#51afef" :inherit (bold)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#51afef" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#51afef" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#98be65"))))
 '(font-lock-type-face ((t (:foreground "#ECBE7B"))))
 '(font-lock-variable-name-face ((t (:foreground "#dcaeea"))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#51afef"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#3f444a" :inherit (default)))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#bbc2cf" :background "#21242b"))))
 '(mode-line ((t (:box nil :background "#1c1e24"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#bbc2cf"))))
 '(mode-line-emphasis ((t (:foreground "#51afef"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#545668" :background "#1d2026"))))
 '(isearch ((t (:weight bold :foreground "#1B2229" :background "#51afef"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:weight bold :foreground "#DFDFDF" :background "#2257A0"))))
 '(match ((t (:weight bold :foreground "#98be65" :background "#1B2229"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'mariana-theme)
